<?php
use yii\db\Migration;
/**
 * Handles the creation of table `{{%role_methods}}`.
 */
class m200401_105600_create_role_methods_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%role_methods}}', [
            'id' => $this->primaryKey(),
            'role_id' => $this->integer()->comment("Роль"),
            'method_id' => $this->integer()->comment("Метод"),
            'value' => $this->integer()->comment("Значение"),
        ]);

        $this->createIndex(
            '{{%idx-role_methods-role_id}}',
            '{{%role_methods}}',
            'role_id'
        );

        // add foreign key for table `{{%roles}}`
        $this->addForeignKey(
            '{{%fk-role_methods-role_id}}',
            '{{%role_methods}}',
            'role_id',
            '{{%roles}}',
            'id',
            'CASCADE'
        );

        $this->createIndex(
            '{{%idx-role_methods-method_id}}',
            '{{%role_methods}}',
            'method_id'
        );

        // add foreign key for table `{{%roles}}`
        $this->addForeignKey(
            '{{%fk-role_methods-method_id}}',
            '{{%role_methods}}',
            'method_id',
            '{{%module_methods}}',
            'id',
            'CASCADE'
        );
        /**
         * Супер админ uchun methodlar berish
         * Barcha metodlarni statusi true
         * */
        // $super_admin = array(
        //     array('role_id' => 7, 'method_id' => 1, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 2, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 3, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 4, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 5, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 6, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 7, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 8, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 9, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 10, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 11, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 12, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 13, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 14, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 15, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 16, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 17, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 18, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 19, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 20, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 21, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 22, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 23, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 24, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 25, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 26, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 27, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 28, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 29, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 30, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 31, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 32, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 33, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 34, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 35, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 36, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 37, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 38, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 39, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 40, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 41, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 42, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 43, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 44, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 45, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 46, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 47, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 48, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 49, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 50, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 51, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 52, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 53, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 54, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 55, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 56, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 57, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 58, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 59, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 60, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 61, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 62, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 63, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 64, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 65, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 66, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 67, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 68, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 69, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 70, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 71, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 72, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 73, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 74, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 75, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 76, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 77, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 78, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 79, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 80, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 81, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 82, 'value' => 1),
        //     array('role_id' => 7, 'method_id' => 83, 'value' => 1),
        // );
        // foreach ($super_admin as $value) $this->insert('role_methods', $value);
        /*
         * Главный администратор huquqlarini berib chiqamiz
         * */
        // $admin = array(
        //     array('role_id' => 23, 'method_id' => 1, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 2, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 3, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 4, 'value' => 0),
        //     array('role_id' => 23, 'method_id' => 5, 'value' => 0),
        //     array('role_id' => 23, 'method_id' => 6, 'value' => 0),
        //     array('role_id' => 23, 'method_id' => 7, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 8, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 9, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 10, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 11, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 12, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 13, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 14, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 15, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 16, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 17, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 18, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 19, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 20, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 21, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 22, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 23, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 24, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 25, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 26, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 27, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 28, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 29, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 30, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 31, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 32, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 33, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 34, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 35, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 36, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 37, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 38, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 39, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 40, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 41, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 42, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 43, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 44, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 45, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 46, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 47, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 48, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 49, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 50, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 51, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 52, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 53, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 54, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 55, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 56, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 57, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 58, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 59, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 60, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 61, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 62, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 63, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 64, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 65, 'value' => 0),
        //     array('role_id' => 23, 'method_id' => 66, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 67, 'value' => 0),
        //     array('role_id' => 23, 'method_id' => 68, 'value' => 0),
        //     array('role_id' => 23, 'method_id' => 69, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 70, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 71, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 72, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 73, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 74, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 75, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 76, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 77, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 78, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 79, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 80, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 81, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 82, 'value' => 1),
        //     array('role_id' => 23, 'method_id' => 83, 'value' => 1),
        // );
        // foreach ($admin as $value) $this->insert('role_methods', $value);
        /*SEO-Специалист uchun huquqlar*/
        // $seo = array(
        //     array('role_id' => 24, 'method_id' => 1, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 2, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 3, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 4, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 5, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 6, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 7, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 8, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 9, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 10, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 11, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 12, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 13, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 14, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 15, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 16, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 17, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 18, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 19, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 20, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 21, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 22, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 23, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 24, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 25, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 26, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 27, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 28, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 29, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 30, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 31, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 32, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 33, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 34, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 35, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 36, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 37, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 38, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 39, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 40, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 41, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 42, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 43, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 44, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 45, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 46, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 47, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 48, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 49, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 50, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 51, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 52, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 53, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 54, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 55, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 56, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 57, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 58, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 59, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 60, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 61, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 62, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 63, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 64, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 65, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 66, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 67, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 68, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 69, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 70, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 71, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 72, 'value' => 1),
        //     array('role_id' => 24, 'method_id' => 73, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 74, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 75, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 76, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 77, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 78, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 79, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 80, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 81, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 82, 'value' => 0),
        //     array('role_id' => 24, 'method_id' => 83, 'value' => 0),
        // );
        // foreach ($seo as $value) $this->insert('role_methods', $value);
        /*Модератор huquqlari*/
        // $moderator = array(
        //     array('role_id' => 17, 'method_id' => 1, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 2, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 3, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 4, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 5, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 6, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 7, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 8, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 9, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 10, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 11, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 12, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 13, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 14, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 15, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 16, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 17, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 18, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 19, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 20, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 21, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 22, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 23, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 24, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 25, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 26, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 27, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 28, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 29, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 30, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 31, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 32, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 33, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 34, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 35, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 36, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 37, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 38, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 39, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 40, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 41, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 42, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 43, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 44, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 45, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 46, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 47, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 48, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 49, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 50, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 51, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 52, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 53, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 54, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 55, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 56, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 57, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 58, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 59, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 60, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 61, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 62, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 63, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 64, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 65, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 66, 'value' => 1),
        //     array('role_id' => 17, 'method_id' => 67, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 68, 'value' => 1),
        //     array('role_id' => 17, 'method_id' => 69, 'value' => 1),
        //     array('role_id' => 17, 'method_id' => 70, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 71, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 72, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 73, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 74, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 75, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 76, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 77, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 78, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 79, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 80, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 81, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 82, 'value' => 0),
        //     array('role_id' => 17, 'method_id' => 83, 'value' => 0),
        // );
        // foreach ($moderator as $value) $this->insert('role_methods', $value);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {   
        $this->dropForeignKey(
            '{{%fk-role_methods-role_id}}',
            '{{%role_methods}}'
        );

        // drops index for column `role_id`
        $this->dropIndex(
            '{{%idx-role_methods-role_id}}',
            '{{%role_methods}}'
        );
         $this->dropForeignKey(
            '{{%fk-role_methods-method_id}}',
            '{{%role_methods}}'
        );

        // drops index for column `method_id`
        $this->dropIndex(
            '{{%idx-role_methods-method_id}}',
            '{{%role_methods}}'
        );

        $this->dropTable('{{%role_methods}}');
    }
}
