<?php
return [
    'adminka' => 'https://' . $_SERVER['SERVER_NAME'],
    'site_name' => 'https://bisyor.uz',
    'itemLink' => 'https://bisyor.uz/obyavlenie/',
    'userAuth' => 'https://bisyor.uz/user-auth',
    'adminEmail' => 'support@bisyo.ruz',
    'image_site' => 'https://img.bisyor.uz',
    'itemsPath' => 'https://img.bisyor.uz/web/uploads/items/',
    'blogsPath' => 'https://img.bisyor.uz/web/uploads/blog_posts/',
    'host' => [
    	'name' => '188.127.250.69',
	    'username' => 'img',
	    'password' => '0S6t1N8v'
    ],
    'paginationSizeChats' => 20,
    'paginationSizeChatsUsersList' => 20,
    'currenciesCours' => 'https://cbu.uz/oz/arkhiv-kursov-valyut/json/',
    'settingsUrl' => 'https://bisyor.uz/download',
    'robotsUrl' => 'https://bisyor.uz/download-robots',
    'siteCategoryUrl' => 'https://bisyor.uz/obyavlenie/list/',
    'blogUrl' => 'https://bisyor.uz/blogs/',
    'shopUrl' => 'https://bisyor.uz/shops/',
    'sitemapPath' => 'https://bisyor.uz/sitemaps/',
    'downloadSitemapUrl' => 'https://bisyor.uz/download-sitemap',
    'downloadSitemapImageUrl' => 'https://bisyor.uz/download-sitemap-image',
    'downloadPopularSitemapUrl' => 'https://bisyor.uz/download-popular-sitemap',
    'runHandle' => 'https://dash.bisyor.uz/references/api/sitemap',
    'itemImagePath' => 'https://img.bisyor.uz/web/uploads/items/',
    'botToken' => '438602299:AAHakjDdzvmJw_bjilVt-88OPLfN9MgUHkk',
    'smsServisPassword' => '4MbwqskBsN9JAM1C1af6WBsb1IJSoAWvMsT3SHPY',
    'smsServisEmail' => 'info@zamin.uz',
    'popularSearchKeywordUrl' => 'https://bisyor.uz/search?query=',
    'itemClearCache' => 'https://bisyor.uz/clear-item-cache/',
    'billCreateUrl' => 'https://api.bisyor.uz/api/v1/additional/create-bill',
    'fireBase' => 'AAAAi1s9F_w:APA91bECQOvpeq7wmxxlqkSXXO_En1UdiDVfp50-gvRScvol0Punk9F3EMPYk86ALHgpAtrg36fOrwJrMN-cb0npBag7UwU5phatHDIPdQWqfmIfiGlz6T0rjtA4dy99Wl8jPJy8GdNi',
];
