<?php
 return [
     'logo'=>'bisyor-logo.svg',
     'name'=>'Bisyor',
     'email'=>'support@bisyor.uz',
     'facebook'=>'https://facebook.com/bisyor',
     'twitter'=>'https://twitter.com/bisyor_uz',
     'instagram'=>'https://instagram.com/bisyoruz',
     'youtube'=>'https://youtube.com/bisyor',
     'telegram'=>'https://t.me/bisyor',
     'odnoklassniki'=>'https://ok.ru/bisyor',
     'site_name'=>'www.bisyor.uz',
     'adminka'=>'www.bisyor.uz',
     'seo_site_name'=>'www.bisyor.uz',
     'alert_site_name'=>'Bisyor.uz',
     'contacts_form_title'=>'Заголовок страницы',
     'reason_block'=>'',
     'contacts_form_header'=>'',
     'enabled'=>'1',
     'item_author'=>'3',
     'general_publication_authorized'=>'0',
     'general_publication_pre_moderation'=>'1',
     'general_publication_pre_moderation_update'=>'1',
     'general_editing_item_category'=>'0',
     'general_agreement_submitting_item'=>'0',
     'general_activation_link_expiration_day'=>'3',
     'general_re_publishing_raise'=>'0',
     'general_auto_deletion_item'=>'0',
     'general_deleting_inactive_user_items'=>'0',
     'general_sms_alert'=>'0',
     'general_user_items_pagesize'=>'20',
     'general_limits_payed'=>'1',
     'general_automatic_translation'=>'0',
     'search_sphinx'=>'0',
     'search_list_type'=>'1',
     'search_category_currency'=>'0',
     'search_pagesize'=>'18',
     'search_quick_limit'=>'5',
     'search_quick_category'=>'0',
     'search_filter_catslevel'=>'8',
     'search_premium_limit'=>'4',
     'search_premium_category'=>'0',
     'search_premium_region'=>'0',
     'search_premium_rand'=>'1',
     'search_rss_enabled'=>'0',
     'search_rss_limit'=>'18',
     'view_similar_limit'=>'6',
     'view_comments'=>'0',
     'view_promote'=>'0',
     'index_region_search'=>'1',
     'index_region_search_canonical'=>'1',
     'import_access'=>'2',
     'import_csv_frontend'=>'1',
     'import_update_republicate'=>'1',
     'address'=>'Узбекистан, Ташкент, Чиланзарский район, 1-й квартал, 4',
     'general_announcement_period'=>'1',
     'phone'=>'+99871-200-02-09',
     'import_cleanup'=>'30',
     'import_title_auto'=>'1',
     'seo_filter_cats_empty'=>'1',
     'seo_cats_empty_index'=>'1',
     'google_play'=>'https://play.google.com/store/apps/details?id=uz.bisyor',
     'seo_view_meta_description_limit'=>'150',
     'shops_search_sphinx'=>'1',
     'shops_premoderation'=>'1',
     'shops_categories'=>'1',
     'shops_category_count'=>'20',
     'shops_categories_limit'=>'20',
     'shops_abonement'=>'1',
     'shops_abonement_default_limit'=>'10',
     'shops_form_title_limit'=>'50',
     'shops_form_descr_limit'=>'1000',
     'shops_phones_limit'=>'4',
     'shops_social_limit'=>'5',
     'shop_items_pagesize'=>'18',
     'users_register_type'=>'2',
     'users_register_phone_contacts'=>'0',
     'users_register_captcha'=>'0',
     'users_register_passconfirm'=>'1',
     'users_register_social_email_activation'=>'1',
     'users_profile_phones'=>'2',
     'users_settings_contacts'=>'1',
     'users_settings_email_change'=>'1',
     'users_email_temporary_check'=>'0',
     'users_fake_email_template'=>'{name}-fake@{host}',
     'users_sms_retry_limit'=>'3',
     'users_sms_retry_timeout'=>'3',
     'users_sms_code_type'=>'2',
     'users_sms_code_length'=>'4',
     'users_sms_links_short'=>'0',
     'internalmail_attachments'=>'1',
     'internalmail_folders'=>'1',
     'internalmail_users_write_form_captcha'=>'0',
     'internalmail_users_write_form_logined'=>'0',
     'internalmail_contacts_limit'=>'0',
     'blog_list_pagesize'=>'8',
     'blog_list_category_pagesize'=>'8',
     'blog_categories'=>'1',
     'blog_tags'=>'1',
     'blog_tags_cloud_limit'=>'3',
     'blog_list_tag_pagesize'=>'8',
     'blog_last_block_limit'=>'3',
     'blog_last_block_preview'=>'1',
     'help_search_pagesize'=>'10',
     'help_questions_form_wysiwyg'=>'1',
     'contacts_captcha'=>'1',
     'contacts_from_sender'=>'1',
     'geo_ip_location'=>'1',
     'geo_maps_type'=>'2',
     'geo_maps_googleKey'=>'AIzaSyAyd6T1QtWogL-bDRSQOGyCsdgF1Luklo0',
     'geo_maps_default_coords_x'=>'55.7481',
     'geo_maps_default_coords_y'=>'37.6206',
     'geo_districts'=>'1',
     'geo_filter_url'=>'2',
     'geo_city_select_presuggest_limit'=>'15',
     'seo_meta_limit_mtitle'=>'1000',
     'seo_meta_limit_mkeywords'=>'250',
     'seo_meta_limit_mdescription'=>'300',
     'seo_landing_pages_enabled'=>'1',
     'seo_redirects'=>'1',
     'seo_lists_empty_index'=>'1',
     'seo_pages_index'=>'1',
     'seo_pages_canonical'=>'1',
     'seo_site_sitemapXML_langs'=>'2',
     'other_currency_default'=>'1',
     'other_currency_rate_auto'=>'0',
     'other_locale_accepted_languages'=>'1',
     'other_site_static_minify'=>'1',
     'other_site_static_minify_bundle'=>'1',
     'other_sphinx_enabled'=>'1',
     'other_sphinx_host'=>'127.0.0.1',
     'other_sphinx_port'=>'9306',
     'other_sphinx_path'=>'/var/lib/sphinx/',
     'other_sphinx_version'=>'2.2.11',
     'other_mail_fromname'=>'Bisyor.uz',
     'other_mail_noreply'=>'noreply@bisyor.uz',
     'other_mail_admin'=>'admin@bisyor.uz',
     'other_mail_method'=>'1',
     'other_https_only'=>'1',
     'other_https_redirect'=>'1',
     'other_hh_mailcheck_enabled'=>'1',
     'other_hh_stat_allowed'=>'1',
     'the_term_of_ad_renewal_period_365'=>'365',
     'notify_users_of_the_completion_of_publishing_ads_the_1_day'=>'1',
     'notify_users_of_the_completion_of_publishing_ads_the_2_day'=>'1',
     'notify_users_of_the_completion_of_publishing_ads_the_5_day'=>'1',
     'code_for_the_page_view_ads'=>'<script type="text/javascript">(function() {
                              if (window.pluso)if (typeof window.pluso.start == "function") return;
                              if (window.ifpluso==undefined) { window.ifpluso = 1;
                                var d = document, s = d.createElement("script"), g = "getElementsByTagName";
                                s.type = "text/javascript"; s.charset="UTF-8"; s.async = true;
                                s.src = ("https:" == window.location.protocol ? "https" : "http")  + "://share.pluso.ru/pluso-like.js";
                                var h=d[g]("body")[0];
                                h.appendChild(s);
                              }})();</script>
                            <div class="pluso" data-background="transparent" data-options="small,round,line,horizontal,nocounter,theme=06" data-services="facebook,vkontakte,google,twitter,odnoklassniki,moimir,yandex"></div>',
     'general_item_count_in_new_items'=>'20',
     'period_items_count'=>'30',
     'view_statistic_available'=>'0',
     'users_settings_destroy'=>'0',
     'blog_view_sharecode'=>'<script type="text/javascript">(function() {
                              if (window.pluso)if (typeof window.pluso.start == "function") return;
                              if (window.ifpluso==undefined) { window.ifpluso = 1;
                                var d = document, s = d.createElement("script"), g = "getElementsByTagName";
                                s.type = "text/javascript"; s.charset="UTF-8"; s.async = true;
                                s.src = ("https:" == window.location.protocol ? "https" : "http")  + "://share.pluso.ru/pluso-like.js";
                                var h=d[g]("body")[0];
                                h.appendChild(s);
                              }})();</script>
                            <div class="pluso" data-background="transparent" data-options="small,round,line,horizontal,nocounter,theme=06" data-services="facebook,vkontakte,google,twitter,odnoklassniki,moimir,yandex"></div>',
     'other_date_timezone'=>'Asia/Samarkand',
     'copyright'=>'<p>Bisyor &mdash; Digital Store</p>',
     'the_term_of_publication_of_the_announcement'=>'90',
     'contacts_form_text'=>'<p>Текст страницы</p>',
     'coordinate_x'=>'41.28701452360781',
     'coordinate_y'=>'69.22842702636495',
     'telegram_bot_token'=>'438602299:AAHakjDdzvmJw_bjilVt-88OPLfN9MgUHkk',
     'app_store'=>'#',
     'last_item_count_in_new_items'=>'10',
     'recommendation_count'=>'25',
     'geo_maps_yandexKey'=>'2f80532e-919c-44e6-9334-2d6aaf4870cd',
     'recommendation_categories_count'=>'7',
     'bonus_to_the_user_for_entering_the_platform_once_a_day'=>'100',
     'bonus_for_user'=>'0',
     'general_premium_view_type'=>'1',
     'telegram_bot'=>'https://t.me/bisyorbot',
     'sms_service_token'=>'c7TE7cl4RemAbuKFBqocuG:APA91bHDSWrXq0oLRNiqQO7N6iXmhMYR3wvGa8NG1TpjotQX9HMXxFs8SPtrr3eZxM_Km_JDvJ9zOMt87rFbZb6tvTikWpIe3DvgZA8sTuTVTaow5FNkO2Tg4aJ7z3WAWwLbEfv-CFhC',
     'sms_service'=>'1',
     'footer_text'=>'2130 предложений от 119 магазинов.<br>Обновлено в 17:30 29.04.2022',
     'sms_service_message'=>'Ваш код на bisyor.uz',

];
?>
