<?php

namespace backend\models\mail;

use Yii;
use yii\helpers\Html;

/**
 * This is the model class for table "sendmail_template".
 *
 * @property int $id ID
 * @property string|null $title Заголовок
 * @property string|null $content Текст шаблона
 * @property bool|null $is_html HTML
 * @property int|null $num Номер
 * @property string|null $date_cr Дата создание
 * @property string|null $date_up Дата изменение
 *
 * @property SendmailMassend[] $sendmailMassends
 */
class SendmailTemplate extends \yii\db\ActiveRecord
{
    public $translation_title;
    public $translation_content;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sendmail_template';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['content'], 'string'],
            [['is_html'], 'boolean'],
            [['title', 'content'], 'required'],
            [['num'], 'default', 'value' => null],
            [['num'], 'integer'],
            [['date_cr', 'date_up'], 'safe'],
            [['title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'content' => 'Текст шаблона',
            'is_html' => 'HTML',
            'num' => 'Номер',
            'date_cr' => 'Дата создание',
            'date_up' => 'Дата изменение',
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {
        if($insert){
            if($this->isNewRecord){
                $this->date_cr = date("Y-m-d H:i:s");
            }else{
                $this->date_up = date("Y-m-d H:i:s");
            }
        }
        if($this->is_html == false) $this->content = Html::encode($this->content);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


    /**
     * Gets query for [[SendmailMassends]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getSendmailMassends()
    {
        return $this->hasMany(SendmailMassend::className(), ['template_id' => 'id']);
    }


    /**
     * @return string[]
     */
    public static function needTranslation()
    {
        return [
            'title' => 'translation_title',
            'content' => 'translation_content',
        ];
    }
}
